name: Daily Year Progress Update

on:
  schedule:
    - cron: '0 13 * * *'  # Runs at 8 every day
  push:
    branches: [ main ]  # Or your default branch

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the entire history is checked out
          token: ${{ secrets.GIT_TOKEN }}
      - name: Update Year Progress
        run: |
          python progress.py > README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update Year Progress"
          git push
